app/config/routes.rb
Rails.application.routes.draw do
  
  resources :vehicles
  resources :users
  resources :services
  resources :finances
  
  root 'users#index'
  
  

end

app/app/models/finance.rb
class Finance < ActiveRecord::Base
end

app/app/models/service.rb
class Service < ActiveRecord::Base
    validates_presence_of :motor, :cambio, :geral, :manutencao
    belongs_to :vehicle
end

app/app/models/user.rb
class User < ActiveRecord::Base
    #Valida os campos nome, endereco, telefone
    validates_presence_of :name, :address, :phone, :rg
    validates_email_format_of :email, :message => 'inválido'

    has_many :vehicle
end

app/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
    validates_presence_of :plate, :brand, :model, :color, :displacement
    belongs_to :user
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def index
    
  end
  
end

app/app/controllers/finance_controller.rb
class FinanceController < ApplicationController
end

app/app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end
    
  # GET /services/1
  # GET /services/1.json  
  def show
  end
    
  # GET /services/new
  def new
    @service = Service.new
    @vehicles = Hash.new
    Vehicle.all.each do |u|
        @vehicles.store(u[:name], u[:id])
    end
  end  
    
  # GET /services/1/edit
  def edit
  end
  
  # POST /services
  # POST /services.json    
  def create
    
    @service = Service.new(service_params)

    respond_to do |format|
      
      if @service.save
        @service.user = Vehicle.find(vehicle_params[:vehicle])
        format.html { redirect_to @service, notice: 'criado com sucesso.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
   end
  end
    
  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @vehicle, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service}
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:motor, :cambio, :geral, :manutencao)
    end
end
 

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :address, :email, :rg, :phone)
    end
end

app/app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    @users = Hash.new
    User.all.each do |u|
        @users.store(u[:name], u[:id])
    end
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create

    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|

      if @vehicle.save
        @vehicle.user = User.find(vehicle_params[:user])
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:plate, :brand, :model, :color, :fuel, :displacement)
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/finance_helper.rb
module FinanceHelper
end

app/app/helpers/services_helper.rb
module ServicesHelper
    def belongs_to_vehicle(service)
    end
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/helpers/vehicles_helper.rb
module VehiclesHelper
  def belongs_to_user(vehicle)
    user_signed_in? && vehicle.user == current_user
  end
end

app/app/views/applications/index.html.haml
-# This file is app/view/movies/index.html.haml

%h1 All Movies

%p
  = form_tag movies_path, :id => "ratings_form", :method => :get, :class => "form-inline" do
    Include 
    - @all_ratings.each do |rating|
      = rating
      = check_box_tag "ratings[#{rating}]", 1, @ratings.include?(rating), :id => "ratings_#{rating}", class: "checkbox"
    = submit_tag "Refresh", :id => "ratings_submit", class: "btn btn-default"
  
  
%table#movies.table 
  %thead
    %tr
      %th{params[:sort] == "title" ? {class: "hilite"} : {}}
        = link_to "Movie Title", movies_path(:sort => "title"), :id => "title_header"
        %span.glyphicon{params[:sort] == "title" ? {class: "glyphicon-star"} : {}} 
      %th Rating
      %th{params[:sort] == "release_date" ? {class: "hilite"} : {}}
        = link_to "Release Date", movies_path(:sort => "release_date"), :id => "release_date_header"
        %span.glyphicon{params[:sort] == "release_date" ? {class: "glyphicon-star"} : {}} 
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to raw('Info'),movie_path(movie), class: "btn btn-primary"
     
     
= link_to 'Add Movie', new_movie_path, class: "btn btn-primary"

app/app/views/layouts/_messages.html.haml
-# app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/app/views/layouts/application.html.haml
-# app/views/layouts/application.html.haml

-# Jam in a flash[:notice] so that we can see the flash rendering in effect
- flash[:notice] = "This is message in flash"
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "App_Name"
    %meta{:content => content_for?(:description) ? yield(:description) : "App_Name", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse

      %nav.navbar{:role => "navigation"}
        .container-fluid
          .navbar-header
            %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "#"} Retífica Automotiva Grales
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Usuários
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    %a{:href => "/users"} Listar Usuários
                  %li
                    %a{:href => "/users/new"} Adicionar Usuário
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Veículos
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    %a{:href => "/vehicles"} Listar Veículos
                  %li
                    %a{:href => "/vehicles/new"} Adicionar Veículo
                    
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Serviços
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    %a{:href => "/vehicles"} Consultar Serviços
                    
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Finanças
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    %a{:href => "/finances"} Listar Finanças
                  %li
                    %a{:href => "/financers/new"} Adicionar Finanças
                    
              %form.navbar-form.navbar-right{:role => "Buscar"}
                .form-group
                  %input.form-control{:placeholder => "Buscar", :type => "text"}
                %button.btn.btn-default{:type => "submit"} Submit

    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              space
          .row
            .span12
              = render 'layouts/messages'
              = yield

    %footer

app/app/views/services/_form.html.haml
.row
  .col-xs-4
    = form_for @service, class: "form" do |f|
      - if @service.errors.any?
        #error_explanation
          %h2= "#{pluralize(@service.errors.count, "erro")} foram encontrados, por favor verifique "
          %ul
            - @service.errors.full_messages.each do |msg|
              %li= msg

      .field
        = f.label :motor
        = f.text_field :motor, class: "form-control"
      .field
        = f.label :cambio
        = f.text_field :cambio, class: "form-control"  
      .field
        = f.label :geral
        = f.text_field :geral, class: "form-control"
      .field
        = f.label :manutencao
        = f.text_field :manutencao, class: "form-control"  
      .actions
        = f.submit 'Save', class: "btn btn-primary"

app/app/views/services/edit.html.haml
%h1 Editing Service

= render 'form'

= link_to 'Mostrar', @service
\|
= link_to 'Voltar', services_path

app/app/views/services/index.html.haml
%h1 Serviços

%table.table
  %thead
    %tr
      %th retífica do motor
      %th retífica de câmbio automático
      %th mecânica geral
      %th manutenção
      %th
      %th
      %th

  %tbody
    - @services.each do |service|
      %tr
       %td= service.vehicle.name
        %td= service.motor
        %td= service.cambio
        %td= service.geral
        %td= service.manutencao
        %td= link_to 'Show', service
        
%br

= link_to 'Serviços', new_service_path

app/app/views/services/new.html.haml
%h1 Serviço

= render 'form'

= link_to 'Voltar', services_path

app/app/views/services/show.html.haml
%p#notice= notice

%p
  %b retifíca de motor:
  = @service.motor
%p
  %b retífica de câmbio automático:
  = @service.cambio
%p
  %b serviço de mecânica geral:
  = @service.geral
%p
  %b serviço de manutenção:
  = @service.manutencao

= link_to 'Editar', edit_service_path(@service)
\|
= link_to 'Voltar', services_path

app/app/views/users/_form.html.haml
.row
  .col-xs-4
    = form_for @user, class: "form" do |f|
      - if @user.errors.any?
        #error_explanation
          %h2= "#{pluralize(@user.errors.count, "erro")} foram encontrados, por favor verifique "
          %ul
            - @user.errors.full_messages.each do |msg|
              %li= msg

      .field
        = f.label :name
        = f.text_field :name, class: "form-control"
      .field
        = f.label :address
        = f.text_field :address, class: "form-control"
      .field
        = f.label :email
        = f.text_field :email, class: "form-control"
      .field
        = f.label :rg
        = f.text_field :rg, class: "form-control"
      .field
        = f.label :phone
        = f.text_field :phone, class: "form-control"
      .actions
        = f.submit 'Save', class: "btn btn-primary"

app/app/views/users/edit.html.haml
%h1 Editar Usuário

= render 'form'

= link_to 'Mostrar', @user
\|
= link_to 'Voltar', users_path

app/app/views/users/index.html.haml
%h1 Usuários Cadastrados

%table.table
  %thead
    %tr
      %th Nome
      %th Endereço
      %th Email
      %th RG
      %th Contato
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.address
        %td= user.email
        %td= user.rg
        %td= user.phone
        %td= link_to 'Mostrar', user, class: "btn btn-primary"
        %td= link_to 'Editar', edit_user_path(user), class: "btn btn-primary"
        %td= link_to 'Deletar', user, class: "btn btn-primary", :method => :delete, :data => { :confirm => 'Você tem certeza?' }

%br

= link_to 'Novo Usuário', new_user_path

app/app/views/users/new.html.haml
%h1 Novo Usuário

= render 'form'

= link_to 'Voltar', users_path

app/app/views/users/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @user.name
%p
  %b Endereço:
  = @user.address
%p
  %b Email:
  = @user.email
%p
  %b RG:
  = @user.rg
%p
  %b Contato:
  = @user.phone

= link_to 'Editar', edit_user_path(@user)
\|
= link_to 'Voltar', users_path

app/app/views/vehicles/_form.html.haml
.row
  .col-xs-4
    = form_for @vehicle do |f|
      - if @vehicle.errors.any?
        #error_explanation
          %h2= "#{pluralize(@vehicle.errors.count, "erro")} foram encontrados, por favor verifique"
          %ul
            - @vehicle.errors.full_messages.each do |msg|
              %li= msg
      .field
        = f.label :user
        = f.select :user, @users
      .field
        = f.label :plate
        = f.text_field :plate, class: "form-control"
      .field
        = f.label :brand
        = f.text_field :brand,  class: "form-control"
      .field
        = f.label :model
        = f.text_field :model, class: "form-control"
      .field
        = f.label :color
        = f.text_field :color, class: "form-control"
      .field
        = f.label :fuel
        = f.select :fuel, { "Álcool" => "Álcool", "Gasolina" => "Gasolina", "Diesel" => "Diesel", "GNV" => "GNV", "Elétrico" => "Elétrico"}
      .field
        = f.label :displacement
        = f.text_field :displacement, class: "form-control"
      .actions
        = f.submit 'Salvar'

app/app/views/vehicles/edit.html.haml
%h1 Editing vehicle

= render 'form'

= link_to 'Mostrar', @vehicle
\|
= link_to 'Voltar', vehicles_path

app/app/views/vehicles/index.html.haml
%h1 Veículos

%table.table
  %thead
    %tr
      %th Proprietario
      %th Placa
      %th Marca
      %th Modelo
      %th Cor
      %th Combustível
      %th Cilindrada do Motor
      %th
      %th
      %th

  %tbody
    - @vehicles.each do |vehicle|
      %tr
        %td= vehicle.user.name
        %td= vehicle.plate
        %td= vehicle.brand
        %td= vehicle.model
        %td= vehicle.color
        %td= vehicle.fuel
        %td= vehicle.displacement
        %td= link_to 'Show', vehicle
        %td= link_to 'Edit', edit_vehicle_path(vehicle)
        %td= link_to 'Destroy', vehicle, :method => :delete, :data => { :confirm => 'Você tem certeza?' }

%br

= link_to 'Novo Veículo', new_vehicle_path

app/app/views/vehicles/new.html.haml
%h1 Novo Veículo

= render 'form'

= link_to 'Voltar', vehicles_path

app/app/views/vehicles/show.html.haml
%p#notice= notice

%p
  %b Placa:
  = @vehicle.plate
%p
  %b Marca:
  = @vehicle.brand
%p
  %b Modelo:
  = @vehicle.model
%p
  %b Cor:
  = @vehicle.color
%p
  %b Combutível:
  = @vehicle.fuel
%p
  %b Cilindrada:
  = @vehicle.displacement

= link_to 'Editar', edit_vehicle_path(@vehicle)
\|
= link_to 'Voltar', vehicles_path